version: '3.6'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: 
      context: ./backend
    volumes:
      - "./backend:/backend"
      - "backend_node_modules:/backend/node_modules"
    environment:
     NODE_ENV: development
    ports:
      - "3000:3000"
      - "9222:9222"
    entrypoint: ["npm", "run", "debug"]
    depends_on:
      - postgres
    restart: always
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/client
      - frontend_node_modules:/client/node_modules
    depends_on:
      - backend
    
volumes:
  db_data:
  backend_node_modules:
  frontend_node_modules:
