version: '3.6'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - ".:/usr/src/app"
    environment:
     NODE_ENV: development
    ports:
      - "3000:3000"
      - "9222:9222"
    entrypoint: ["npm", "run", "debug"]
    depends_on:
      - postgres
    restart: always
    
volumes:
  db_data:
